# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a243288a0641a1711ea9a7d404db1a7d11e05fd6e6bd628d081a3cb36b8e325686bf2fb613ad240f2f59565701170371f32dd702c32e93573d86d71b9791ae6

test:
  secret_key_base: 919fa1e5f5d0055b48575e7331d3508e13cd1c02201aca13bf8262f965ede73d81a15f5875253ed75d3401129174d2cf0e0c58461b09c228ea601cce887af4c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
